### ISSUE TITLE
Minor: call to `ReentrancyGuard()` constructor unneeded

### ISSUE THREAD

**Issue by pedrorivera** [Vanclief/solidity-imx-bridge#2]
https://github.com/Vanclief/solidity-imx-bridge/blob/e5e824b4bbcb82bd886138aeadbd0803b4d4977e/contracts/bridge/IMXBridge.sol#L34

**Comment by Vanclief** [comment]
https://github.com/Vanclief/solidity-imx-bridge/commit/72613134bb670b6cc54e38b1c8d155d7a7708dfb
