### ISSUE TITLE
Since the `signerAddress` is critical, consider a two step process and emit an event.

### ISSUE THREAD

**Issue by pedrorivera** [Vanclief/solidity-imx-bridge#6]
https://github.com/Vanclief/solidity-imx-bridge/blob/e5e824b4bbcb82bd886138aeadbd0803b4d4977e/contracts/bridge/IMXBridge.sol#L45

The 2-step process protects from unintended transfer of control. The first step proposes the new signerAddress and the second step is the owner of the signerAddress accepting. (OZ ownable works this way)

**Comment by pedrorivera** [comment]
Plus, emit an event to detect an unexpected change

**Comment by Vanclief** [comment]
Can yo provide an example? It is my understanding that Ownable from OZ does not work this way:

```
    /**
     * @dev Transfers ownership of the contract to a new account (`newOwner`).
     * Can only be called by the current owner.
     */
    function transferOwnership(address newOwner) public virtual onlyOwner {
        require(newOwner != address(0), "Ownable: new owner is the zero address");
        _transferOwnership(newOwner);
    }

    /**
     * @dev Transfers ownership of the contract to a new account (`newOwner`).
     * Internal function without access restriction.
     */
    function _transferOwnership(address newOwner) internal virtual {
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
```

I see the importance of emitting an event, but I am not understanding the benefits of doing it in two functions, as it is done by the owner, so for an unintended transfer, the owner account would have to become compromised, doing it on a 2-Step process doesn't add an extra layer, as the compromised owner account would just need to create two transactions. 

Maybe pausing the contract once this transaction is called would be more fitting, as it would mean that the original signing key was compromised. :thinking:

**Comment by Vanclief** [comment]
Added event, and pause: https://github.com/Vanclief/solidity-imx-bridge/commit/85121f6270d3f3e7b29c6c7f5376b360ccc7db68

What do you think?

**Comment by pedrorivera** [comment]
The benefit is in the event that somehow there is a fat finger error when transferring the signing privilege to a different account. It helps because in order to successfully complete the change, you must inherently prove access to the new account by "pulling" the ownership. You can argue it is overprotection, hence "consider".

Only now I realize though that if this happens, you still have the power to change it again because you still control the contract owner. (btw, I may misremember and the two-step thing is from another OZ contract)

**Comment by Vanclief** [comment]
Understood, I agree with the logic (albeit that is a pretty fat finger). The addition of pausing the contract whenever there is a change of signerAddress should be more than enough for preventing major fuckups as it would be kind of a "circuit breaker".

After updating the signerAddress you would have to manually un-pause the contract if it was an intended change, or revert the change to the new signer address.
